language: php

php:
  - 5.6

before_script:
  - composer install --dev --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - ./vendor/bin/test-reporter --coverage-report build/logs/clover.xml