language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - composer install --dev --prefer-dist
  - composer require --dev codeclimate/php-test-reporter

script:
  - ./vendor/bin/phpunit --coverage-clover tmp/clover.xml

after_success:
  - ./vendor/bin/test-reporter --coverage-report tmp/clover.xml